"""empty message

Revision ID: 029e25e55e93
Revises: 
Create Date: 2021-09-29 01:39:29.192690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '029e25e55e93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'bucketlist', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bucketlist', type_='foreignkey')
    # ### end Alembic commands ###
